# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Tea and Techno"
subtitle: "Musings on theology, tea, music production, and the hacker subculture"
name: "Edd Salkield"
email: "edd@salkield.uk"
description: >- # this means to ignore newlines until "baseurl:"
  Musings on theology, tea, and technology.
logo: "assets/images/pixelated_tea.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edd.salkield.uk" # the base hostname & protocol for your site, e.g. http://example.com
locale: "en-GB"
head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js

author:
  name             : "Edd Salkield"
  avatar           : "assets/images/pixelated_tea.jpg"
  bio              : "Christian, hacker, tea drinker"
  location         : "Cambridgeshire, UK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:edd@salkield.uk"
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "Matrix"
      icon: "fas fa-fw fa-comments"
      url: "https://matrix.to/#/@edd:salkield.uk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eddsalkield/"
    - label: "Soundcloud"
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/teaandtechnoofficial"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
